/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Arakoo.ai",
  "tagline": "RAG stack (Retriever Augmented Generative AI) for production LLM applications. On top of Serverless & JSonnet",
  "favicon": "img/logo-arako.ico",
  "url": "https://www.arakoo.ai",
  "baseUrl": "/",
  "organizationName": "arakoodev",
  "projectName": "doc",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "path": "doc",
          "routeBasePath": "doc",
          "sidebarPath": "C:\\Peace\\gsocontributions\\docc\\doc\\sidebars.js",
          "disableVersioning": false
        },
        "blog": {
          "blogTitle": "Blog",
          "path": "blog",
          "routeBasePath": "blog",
          "showReadingTime": true
        },
        "theme": {
          "customCss": "C:\\Peace\\gsocontributions\\docc\\doc\\src\\css\\custom.css"
        }
      }
    ]
  ],
  "plugins": [
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "handbook",
        "path": "C:\\Peace\\gsocontributions\\docc\\doc\\handbook",
        "routeBasePath": "handbook",
        "sidebarPath": "C:\\Peace\\gsocontributions\\docc\\doc\\sidebars2.js"
      }
    ]
  ],
  "themeConfig": {
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "image": "img/code.png",
    "navbar": {
      "logo": {
        "alt": "arakoo Logo",
        "height": 90,
        "src": "img/arakoo-01.png"
      },
      "items": [
        {
          "to": "privacy/",
          "label": "Privacy",
          "position": "right"
        },
        {
          "to": "doc/intro/",
          "activeBasePath": "doc",
          "label": "Doc",
          "position": "right"
        },
        {
          "to": "handbook/intro/",
          "activeBasePath": "handbook",
          "label": "Handbook",
          "position": "right"
        },
        {
          "to": "blog/",
          "label": "Blog",
          "position": "right"
        },
        {
          "href": "https://discord.gg/MtEPK9cnSF",
          "position": "right",
          "className": "navbar__icon navbar__discord"
        },
        {
          "href": "https://github.com/arakoodev",
          "position": "right",
          "className": "navbar__icon navbar__github"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "light",
      "logo": {
        "alt": "Meta Open Source Logo",
        "src": "img/arakoo-01.png",
        "href": "https://opensource.fb.com"
      },
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Docs",
              "to": "/doc/intro"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Stack Overflow",
              "href": "https://stackoverflow.com/questions/tagged/arakoo"
            },
            {
              "label": "Discord",
              "href": "https://discord.gg/MtEPK9cnSF"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/arakooai"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/arakoodev"
            }
          ]
        }
      ]
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
